config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"

  devise_for :users
  resources :connections, only: %i[ index new create destroy ]

  resources :contractors do
    resources :jobs, only: %i[ new create edit update destroy ]
    resources :ratings, only: %i[ new create edit update ]
  end

  namespace :admin do
    resources :users, only: %i[ index show ] do
      member do
        post :reset_password
      end
    end
    resources :contractors, only: %i[ index ]
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :user
  belongs_to :contractor
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_contractor
  before_action :set_job, only: %i[ edit update destroy ]

  # GET /jobs/new
  def new
    @job = @contractor.jobs.new
  end

  # GET /jobs/1/edit
  def edit; end

  # POST /jobs or /jobs.json
  def create
    @job = @contractor.jobs.new(job_params)
    @job.user = current_user

    respond_to do |format|
      if @job.save
        format.html { redirect_to @contractor, notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @contractor, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.destroy!

    respond_to do |format|
      format.html { redirect_to contractor_path(@contractor), status: :see_other, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  def set_contractor
    @contractor = Contractor.find(params.expect(:contractor_id))
  end

  def set_job
    @job = @contractor.jobs.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def job_params
    params.expect(job: %i[description state start_date end_date review])
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= form_with(model: [@contractor, job], class: "job-form") do |form| %>
  <% if job.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field">
        <%= form.textarea :description, placeholder: "Job Description", class: "form-input", required: true %>
        <%= form.label :description, class: "form-label floating-label" %>
    </div>
    <div class="field">
      <p>What was the work that <%= @contractor.name %> did?</p>
    </div>
  </div>

  <div class="row">
    <div class="field">
        <%= form.select :state, options_for_select(["Quote", "Planned", "In Progress", "Complete"]),
                        { prompt: "Select State" }, { class: "form-select form-input", required: true } %>
        <%= form.label :state, class: "form-label floating-label" %>
    </div>
    <div class="field">
      <p>What state is the job in? E.G. "Quote", "Planned", "In Progress", "Complete"</p>
    </div>
  </div>

  <div class="row mb-2">
    <div class="field">
      <%= form.label :start_date, class: "form-label" %>
      <%= form.date_field :start_date, class: "form-input date-input" %>
    </div>

    <div class="field">
      <%= form.label :end_date, class: "form-label" %>
      <%= form.date_field :end_date, class: "form-input date-input" %>
    </div>
  </div>

  <div class="row">
    <div class="field">
        <%= form.textarea :review, placeholder: "Review", class: "form-input" %>
        <%= form.label :review, class: "form-label floating-label" %>
      </div>
    <div class="field">
      <p>What did you think of the work that <%= @contractor.name %> did?</p>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/jobs/_job.html.erb
<div id="<%= dom_id job %>" class="card job-card">
  <div class="card-body rounded-corners">

    <% if job.user == current_user %>
      <div class="top-corner-controls">
        <%= link_to edit_contractor_job_path(job.contractor, job), class: "icon-link link-primary" do %>
          <i class="fa-solid fa-pencil"></i>
        <% end %>
        <%= link_to contractor_job_path(job.contractor, job),
                    data: {
                      turbo_method: :delete,
                      turbo_confirm: "Are you sure you want to delete this job?"
                    }, class: "icon-link link-danger" do %>
          <i class="fa-solid fa-trash"></i>
        <% end if (job.contractor.jobs_for_customer(current_user).size > 1) %>
      </div>
    <% end %>

    <p>
      <strong title="Job Description"><i class="fa-solid fa-paint-roller"></i></strong>
      <%= job.description %>
    </p>

    <p>
      <strong title="Job State"><i class="fa-solid fa-clipboard-question"></i></strong>
      <%= job.state.humanize %>
    </p>

    <p>
      <strong><i class="fa-solid fa-calendar-days"></i></strong>
      <%= job.start_date&.to_fs(:rfc822) %> - <%= job.end_date&.to_fs(:rfc822) %>
    </p>

    <% if job.review.present? %>
      <p>
        <strong>Job Review:</strong>
        <%= job.review %>
      </p>
    <% end %>

  </div>
</div>

app/views/jobs/edit.html.erb
<% content_for :title, "Editing job" %>
<main class="container">
  <div class="card form-card">
    <h1>Edit Job</h1>

    <%= render "form", job: @job %>
  </div>

  <hr>

  <div>
    <%= link_to "Back to contractor", contractor_path(@contractor) %>
  </div>
</main>

app/views/jobs/new.html.erb
<% content_for :title, "New job" %>
<main class="container">
  <div class="card form-card">
    <h1>What did <%= @contractor.name %> do for you?</h1>

    <%= render "form", job: @job %>
  </div>

  <hr>

  <div>
    <%= link_to "Back to contractor", contractor_path(@contractor) %>
  </div>
</main>