config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"

  devise_for :users
  resources :connections, only: %i[ index new create destroy ]

  resources :contractors do
    resources :jobs, only: %i[ new create edit update destroy ]
    resources :ratings, only: %i[ new create edit update ]
  end

  namespace :admin do
    resources :users, only: %i[ index show ] do
      member do
        post :reset_password
      end
    end
    resources :contractors, only: %i[ index ]
  end
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :user
  belongs_to :contractor

  validates :contractor_id, uniqueness: { scope: :user_id }
  validate :job_exists_between_user_and_contractor

  def from_number_of_jobs
    user.jobs.where(contractor_id:).size
  end

  def rating_quality # rubocop:disable Metrics/MethodLength
    case overall_rating
    when 0..5
      "bad"
    when 5..7.5
      "average"
    when 7.5..8
      "good"
    when 9..10
      "excellent"
    else
      "unknown"
    end
  end

  private

  def job_exists_between_user_and_contractor
    return if Job.exists?(user_id:, contractor_id:)

    errors.add(:base, "You must add a job for this contactor before you can add a rating.")
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_contractor
  before_action :set_rating, only: %i[ edit update ]

  # GET /ratings/new
  def new
    @rating = @contractor.ratings.new
  end

  # GET /ratings/1/edit
  def edit; end

  # POST /ratings or /ratings.json
  def create
    @rating = @contractor.ratings.new(rating_params)
    @rating.user = current_user

    respond_to do |format|
      if @rating.save
        format.html { redirect_to @contractor, success: "Rating was successfully created." }
        format.json { render :show, status: :created, location: @rating }
      else
        format.html { render :new, status: :unprocessable_entity, error: "Something went wrong creating your rating." }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ratings/1 or /ratings/1.json
  def update
    respond_to do |format|
      if @rating.update(rating_params)
        format.html { redirect_to @contractor, success: "Rating was successfully updated." }
        format.json { render :show, status: :ok, location: @rating }
      else
        format.html { render :edit, status: :unprocessable_entity, error: "Something went wrong updating your rating." }
        format.json { render json: @rating.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_contractor
    @contractor = Contractor.find(params.expect(:contractor_id))
  end

  def set_rating
    @rating = @contractor.ratings.find(params.expect(:id))
  end

  # Only allow a list of trusted parameters through.
  def rating_params
    params.expect(rating: %i[review overall_rating value_rating communication_rating quality_rating tidiness_rating professionalism_rating])
  end
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/ratings/_form.html.erb
<%= form_with(model: [@contractor, rating], data: { controller: "rating-form" }, class: "rating-form") do |form| %>
  <% if rating.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
        <% rating.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field">
      <%= form.textarea :review, placeholder: "Review", class: "form-input" %>
      <%= form.label :review, class: "form-label floating-label" %>
    </div>
    <div>
      <p>What do you think about <%= @contractor.name %>?</p>
    </div>
  </div>

  <div class="row form-range-row">
    <%= form.label :value_rating, "Value", class: "form-label" %>
    <%= form.range_field :value_rating, in: 0..10, step: 1, class: "form-range",
                         data: { rating_form_target: "valueRatingField",
                                 action: "change->rating-form#changeRating" } %>
    <p class="rating-display" data-rating-form-target="valueRatingDisplay"></p>
  </div>

  <div class="row form-range-row">
    <%= form.label :quality_rating, "Quality", class: "form-label" %>
    <%= form.range_field :quality_rating, in: 0..10, step: 1, class: "form-range",
                         data: { rating_form_target: "qualityRatingField",
                                 action: "change->rating-form#changeRating" } %>
    <p class="rating-display" data-rating-form-target="qualityRatingDisplay"></p>
  </div>

  <div class="row form-range-row">
    <%= form.label :tidiness_rating, "Tidiness", class: "form-label" %>
    <%= form.range_field :tidiness_rating, in: 0..10, step: 1, class: "form-range",
                         data: { rating_form_target: "tidinessRatingField",
                                 action: "change->rating-form#changeRating" } %>
    <p class="rating-display" data-rating-form-target="tidinessRatingDisplay"></p>
  </div>

  <div class="row form-range-row">
    <%= form.label :communication_rating, "Communication", class: "form-label" %>
    <%= form.range_field :communication_rating, in: 0..10, step: 1, class: "form-range",
                         data: { rating_form_target: "communicationRatingField",
                                 action: "change->rating-form#changeRating" } %>
    <p class="rating-display" data-rating-form-target="communicationRatingDisplay"></p>
  </div>

  <div class="row form-range-row">
    <%= form.label :professionalism_rating, "Professionalism", class: "form-label" %>
    <%= form.range_field :professionalism_rating, in: 0..10, step: 1, class: "form-range",
                         data: { rating_form_target: "professionalismRatingField",
                                 action: "change->rating-form#changeRating" } %>
    <p class="rating-display" data-rating-form-target="professionalismRatingDisplay"></p>
  </div>

  <div class="row form-range-row">
    <%= form.label :overall_rating, class: "form-label" %>
    <%= form.range_field :overall_rating, in: 0..10, step: 1, class: "form-range",
                         data: { rating_form_target: "overallRatingField",
                                 action: "change->rating-form#changeRating" } %>
    <p class="rating-display" data-rating-form-target="overallRatingDisplay"></p>
  </div>

  <div>
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/ratings/_rating.html.erb
<div id="<%= dom_id rating %>" class="card rating-card <%= "own-rating" if rating.user == current_user %>">
  <div class="card-header <%= rating.rating_quality %>-rating rounded-top-corners">

    <% if rating.user == current_user %>
      <div class="top-corner-controls">
        <%= link_to edit_contractor_rating_path(rating.contractor, rating), class: "btn btn-secondary" do %>
          <i class="fa-solid fa-pencil"></i>
        <% end %>
      </div>
    <% end %>

    <div class="overall-rating">
      <p class="main">Overall rating: <%= rating.overall_rating %></p>
      <p class="small">from  <%= pluralize(rating.from_number_of_jobs, "job") %></p>
    </div>

    <p class="review-text">
      <strong>Review:</strong>
      <%= rating.review %>
    </p>
  </div>

  <div class="card-body">
    <p class="sub-rating">
      <strong>Value:</strong>
      <%= rating.value_rating %>
    </p>

    <p class="sub-rating">
      <strong>Communication:</strong>
      <%= rating.communication_rating %>
    </p>

    <p class="sub-rating">
      <strong>Quality:</strong>
      <%= rating.quality_rating %>
    </p>

    <p class="sub-rating">
      <strong>Tidiness:</strong>
      <%= rating.tidiness_rating %>
    </p>

    <p class="sub-rating">
      <strong>Professionalism:</strong>
      <%= rating.professionalism_rating %>
    </p>
  </div>
  <div class="card-footer">
    <p>
      Rated by: <%= rating.user.first_name %>, <%= time_ago_in_words(rating.updated_at) %> ago
    </p>
  </div>
</div>

app/views/ratings/edit.html.erb
<% content_for :title, "Editing rating" %>

<main class="container">
  <div class="card form-card">
    <h1>Editing your rating for <%= @contractor.name %> </h1>

    <%= render "form", rating: @rating %>
  </div>
  <br>

  <div>
    <%= link_to "Back to contractor", contractor_path(@contractor) %>
  </div>
</main>

app/views/ratings/new.html.erb
<% content_for :title, "New rating" %>

<div class="card form-card">
  <h1>What did you think of <%= @contractor.name %>?</h1>

  <%= render "form", rating: @rating %>
</div>

<hr>

<div>
  <%= link_to "Back to ratings", contractor_path(@contractor) %>
</div>