config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"

  devise_for :users
  resources :connections, only: %i[ index new create destroy ]

  resources :contractors do
    resources :jobs, only: %i[ new create edit update destroy ]
    resources :ratings, only: %i[ new create edit update ]
  end

  namespace :admin do
    resources :users, only: %i[ index show ] do
      member do
        post :reset_password
      end
    end
    resources :contractors, only: %i[ index ]
  end
end

app/views/pages/_about_aside.html.erb
<aside class="main-page" id="about">
  <hr>
  <details>
    <summary>What's this all about?</summary>
    <h3>What's this all about?</h3>
    <p>Radius Contractors is a <strong>community-driven platform</strong> for finding reliable builders—no ads, no tracking, and
      <a href="https://github.com/phil-6/radius-contractors">open source</a>.</p>
    <p>Think of it like <strong>asking a friend for a recommendation</strong>, but on a larger scale.</p>
    <p>🚀 It's free and costs about £15/month to run. If you'd like to support it,
      <a href="http://buymeacoffee.com/purpleriver">buy me a coffee.</a></p>
    <%#= render partial: 'pages/bmc_button' %>
    <div class="for-builders">
      <h4>For Builders</h4>
      <p class="mb-0">Do great work. Get recommended. It’s that simple.</p>
      <p>Got questions? <a href="mailto:contractors@purpleriver.dev">Reach out here</a></p>
    </div>
    <hr>
    <p class="lead">The project is still a work in progress, so if you have any feedback, find any bugs, or want to be kept up to date with
      updates then please <a href="mailto:contractors@purpleriver.dev">let me know.</a></p>
    <ul>What's in the plan:
      <li>Connect with another user using their link ✅</li>
      <li>View your connections ✅</li>
      <li>Remove connections ✅</li>
      <li>Email user when someone connects with them ✅</li>
      <li>Allow trades to be added when creating a contractor ✅</li>
      <li>User Profile Page
        <ul>
          <li>Show Your Connections</li>
          <li>Show Your Contractors</li>
        </ul>
      </li>
      <li>Improve UI in various places
        <ul>
          <li>Increase size of secondary buttons on account forms ✅</li>
          <li>Navigation: Burger Menu for quick access links from anywhere</li>
          <li>Improve getting started process ✅</li>
          <li>Improve rating readability with colours ✅</li>
        </ul>
      </li>
      <li>Allow contractors to be filtered by trades. ✅</li>
      <li>Allow contractors to be searched. ✅</li>
      <li>Show contractors and reviews from 2nd degree connections (Friends of friends). ✅</li>
      <li>Allow connections to your partners - which see the same things you do.</li>
      <li>Allow photos to be added to jobs.</li>
    </ul>
  </details>
</aside>

app/views/pages/_getting_started.html.erb
<div class="getting-started">

  <h2>Getting Started</h2>
  <p>To get useful recommendations, connect with at least one friend.</p>
  <div class="row getting-started-checklist">
    <div class="">
      <ol>
        <li class="<%= "complete" if current_user %>">
            <span class="list-item-number">
              <i class="fa-solid fa-<%= current_user ? "check" : "right-long" %>"></i>
              Step 1:
            </span>
          Sign Up & Log In
        </li>
        <li class="<%= "complete" if current_user && !current_user&.connections&.size&.zero? %>">
          <%#= "✅ " if current_user && !current_user&.connections&.size&.zero? %>
          <span class="list-item-number">
              <i class="fa-solid fa-<%= current_user && !current_user&.connections&.size&.zero? ? "check" : "right-long" %>"></i>
              Step 2:
            </span>
          Invite a friend and make a connection
        </li>
        <li>
            <span class="list-item-number">
              <i class="fa-solid fa-right-long"></i>
              Step 3:
            </span>
          Add a builder you've used, the job they did and give them a rating
        </li>
      </ol>
    </div>

    <div class="whats-next">
      <h3>What's Next?</h3>
      <% unless current_user %>
        <h5>Sign Up and Log In</h5>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-lg btn-primary" %>
        <%= link_to "Log In", new_user_session_path, class: "btn btn-lg btn-primary" %>
      <% else %>

        <% if current_user.connections.size.zero? %>
          <div class="row">
            <div class="col-12 col-sm-7">
              <h5><i class="fa-solid fa-right-long text-secondary"></i> Invite a Friend</h5>
              <p>Copy your connection link and send it to a friend. You'll get an email when they've connected with you!</p>
            </div>
            <div class="col-12 col-sm-4 button-container">
              <%= render partial: "shared/copy_connection_link_button" %>
              <p>or click the link someone has sent you.</p>
            </div>
          </div>
          <%= render partial: "pages/getting_started/add_a_builder" %>
          <%= render partial: 'pages/getting_started/job_but_no_ratings' %>
        <% else %>
          <% if current_user.ratings.size.zero? %>
            <div class="row">
              <div class="col-12 col-sm-7">
                <p>Great! You've made some connections. <i class="text-success fa-solid fa-people-arrows"></i></p>
              </div>
              <div class="col-12 col-sm-4 button-container">
                <%= link_to "View Connections", connections_path, class: "btn btn-sm btn-connection" %>
              </div>
            </div>
            <%= render partial: "pages/getting_started/add_a_builder" %>

            <% unless current_user.viewable_contractors.size.zero? %>
              <div class="row">
                <div class="col-12 col-sm-7">
                  <p>It looks as though your connections have already added some builders. You can add a job and a rating if you've
                    used one of those tradies.</p>
                </div>
                <div class="col-12 col-sm-4 button-container">
                  <%= link_to "Show builders", contractors_path, class: "btn btn-sm btn-builder" %>
                </div>
              </div>
              <%= render partial: 'pages/getting_started/job_but_no_ratings' %>
            <% end %>

          <% end %>
        <% end %>

      <% end %>
    </div>
  </div>

</div>

app/views/pages/index.html.erb
<header class="container main-page">
  <h1 class="page-title brand">Radius Contractors</h1>
  <h2 class="page-subtitle">Find builders recommended by people you trust</h2>
  <p class="lead">
    It's really challenging to find reliable builders. Check-a-trade and MyBuilder are commercial behemoths, focused on their bottom line
    rather than providing a good service to homeowners.
  </p>
  <p class="lead">
    Radius contractors takes a different approach, the builders you can see on here are only those that have been reviewed by people you
    have connected with.
  </p>
  <hr>
</header>

<main class="container">
  <% if current_user && !current_user.ratings.size.zero? %>
    <h2>Welcome Back <%= current_user.first_name %></h2>
    <p>What would you like to do today?</p>
    <div class="row g-2 front-page-buttons">
      <div class="col-4"><%= link_to "Add a contractor", new_contractor_path, class: "btn btn-builder" %></div>
      <div class="col-4"><%= link_to "Add a new connection", new_connection_path, class: "btn btn-connection" %></div>
      <!--      <div class="col-4"><%#= link_to "Add a rating", new_job_path, class: "btn btn-rating" %></div>-->
      <div class="col-4"><%= link_to "Find a new contractor", contractors_path, class: "btn btn-builder" %></div>
      <div class="col-4"><%= link_to "View or edit something you added previously", root_path, class: "btn btn-secondary" %></div>
      <div class="col-4"><%= link_to "Edit your account", edit_user_registration_path, class: "btn btn-primary" %></div>
    </div>
  <% else %>
    <h2>Getting Started</h2>
    <p>For this app to be useful, you need to sign up with at least one other friend, so you can both see each other's recommended
      builders.</p>
    <p>You can sign up from the link below, then you can generate a personalised link invite your friends.</p>
    <p>Once you've signed up, you can add builders you've used, the jobs they've worked or quoted for and give them a rating. When you
      friends
      sign up and do the same thing, you'll be able to see the builders they have rated.</p>
    <p>It requires a bit of community effort, but it's that simple!</p>

    <div class="getting-started-checklist">
      <h3>Your Checklist</h3>
      <ol>
        <li>
          Sign Up and Log In<%= " ✅" if current_user %>
        </li>
        <li>
          Invite a friend and make a connection<%= " ✅" if current_user && !current_user&.connections&.size&.zero? %>
        </li>
        <li>
          Add a builder you've used, the job they did and give them a rating
        </li>
      </ol>

      <h3>What's Next?</h3>
      <% unless current_user %>
        <h5>Sign Up and Log In</h5>
        <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
        <%= link_to "Log In", new_user_session_path, class: "btn btn-primary" %>
      <% else %>
        <% if current_user.connections.size.zero? %>
          <h5>Invite a Friend</h5>
          <%# TODO: Process for generating invite links %>
          <p>Coming Soon</p>
        <% else %>
          <% if current_user.ratings.size.zero? %>
            <h5>Add a builder, a job and a rating.</h5>
            <%= link_to "Add a builder", new_contractor_path, class: "btn btn-builder" %>
            <% unless current_user.viewable_contractors.size.zero? %>
              <p>It looks as though your connections have already added some builders, you can add a job and a rating if you've used one of
                those tradies.</p>
              <%= link_to "Add a job", new_job_path, class: "btn btn-job" %>
              <% if !current_user.jobs.size.zero? && current_user.ratings.size.zero? %>
                <p>It looks as though you've added a job, but not rated that builder.</p>
                <%= link_to "Add a rating", new_rating_path, class: "btn btn-rating" %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </div>
  <% end %>

  <% if current_user %>
    <div class="bottom-0 start-0 m-5">
      <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    </div>
  <% end %>
</main>

app/views/pages/main.html.erb
<header class="main-page">
  <h1 class="page-title brand">Radius Contractors</h1>
  <h2 class="page-subtitle">Find builders recommended by people you trust</h2>
  <p class="challenge"><strong>It's really challenging to find reliable builders.</strong> Big platforms like Check-a-trade and MyBuilder
    prioritize profits over homeowners.</p>
  <p class="different">We’re different. You only see builders rated by people you know.</p>
  <hr>
</header>

<main class="main-page">
  <% if current_user && !current_user.ratings.size.zero? %>
    <div class="welcome-back">
      <h2>Welcome Back <%= current_user.first_name %></h2>
      <p>What would you like to do today?</p>
      <div class="row front-page-buttons">
        <%= link_to "View contractors", contractors_path, class: "btn btn-builder" %>
        <%= link_to "View your connections", connections_path, class: "btn btn-connection" %>
        <%= link_to "Add a new contractor", new_contractor_path, class: "btn btn-builder" %>
        <%= link_to "Add a new connection", new_connection_path, class: "btn btn-connection" %>
        <%= link_to "Edit your account", edit_user_registration_path, class: "btn btn-primary" %>

        <%= link_to root_path, class: "btn btn-rating" do %>
          View your profile <br><span class="small">(coming soon)</span>
        <% end %>
      </div>
    </div>
  <% else %>
    <%= render partial: 'getting_started' %>
  <% end %>
</main>

<%= render partial: 'about_aside' %>

<% if current_user %>
  <div class="sign-out">
    <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
  </div>
<% end %>