config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "pages#index"

  devise_for :users
  resources :connections, only: %i[ index new create destroy ]

  resources :contractors do
    resources :jobs, only: %i[ new create edit update destroy ]
    resources :ratings, only: %i[ new create edit update ]
  end

  namespace :admin do
    resources :users, only: %i[ index show ] do
      member do
        post :reset_password
      end
    end
    resources :contractors, only: %i[ index ]
  end
end

app/models/contractor.rb
class Contractor < ApplicationRecord
  include PgSearch::Model

  belongs_to :added_by, class_name: "User"
  belongs_to :updated_by, class_name: "User", optional: true
  has_many :contractor_trades, dependent: :destroy
  has_many :trades, through: :contractor_trades
  accepts_nested_attributes_for :contractor_trades, allow_destroy: true

  has_many :jobs, dependent: :restrict_with_exception
  has_many :customers, -> { distinct }, through: :jobs, source: :user
  has_many :ratings, dependent: :restrict_with_exception

  before_validation :normalize_blank_values

  validates :name, :number, :town, presence: true
  validates :number, uniqueness: true, format: { with: /\A(?:0|\+?44)(?:\d\s?){9,10}\z/ }
  validates :email, uniqueness: true, allow_nil: true, format: { with: Devise.email_regexp }

  pg_search_scope :search,
                  against: %i[name company_name number email],
                  using: {
                    tsearch: { prefix: true },
                    trigram: { only: :email, threshold: 0.2 }
                  }

  def viewable_jobs(user)
    jobs.where(user_id: user.network_ids_and_self)
  end

  def viewable_customers(user)
    customers.where(id: user.network_ids_and_self)
  end

  def jobs_for_customer(user)
    jobs.where(user_id: user.id)
  end

  def viewable_ratings(user)
    ratings.where(user_id: user.network_ids_and_self)
  end

  def average_rating(user)
    viewable_ratings(user).average(:overall_rating)
  end

  def rating_quality(user) # rubocop:disable Metrics/MethodLength
    case average_rating(user)
    when 0..5
      "bad"
    when 5..7.5
      "average"
    when 7.5..8
      "good"
    when 9..10
      "excellent"
    else
      "unknown"
    end
  end

  private

  def normalize_blank_values
    attributes.each do |column, value|
      self[column] = nil if value.blank?
    end
  end
end

app/controllers/admin/contractors_controller.rb
class Admin::ContractorsController < Admin::BaseController
  def index
    @contractors = Contractor.all
  end
end

app/controllers/contractors_controller.rb
class ContractorsController < ApplicationController
  before_action :set_contractor, only: %i[ show edit update ]
  before_action :set_trades, only: %i[ new edit update ]

  def index
    @contractors = current_user.viewable_contractors
    # @trades = @contractors.map(&:trades).flatten.uniq # Neater but less efficient
    @trades = Trade.where(id: @contractors.joins(:contractor_trades).select(:trade_id))
    @contractors = @contractors.joins(:contractor_trades).where(contractor_trades: { trade_id: params[:trade_id] }) if params[:trade_id].present? # rubocop:disable Layout/LineLength
    @contractors = @contractors.search(params[:search]) if params[:search].present?
  end

  def show
    @user_is_customer = @contractor.customers.include? current_user
    @user_jobs = current_user.jobs.where(contractor_id: @contractor.id)
    @viewable_ratings = @contractor.viewable_ratings(current_user)
    @user_rating = current_user.ratings.find_by(contractor_id: @contractor.id)
  end

  def new
    @contractor = Contractor.new
  end

  def edit
    @contractor_trades = @contractor.contractor_trades
  end

  def create
    @contractor = Contractor.where("number = ? OR email = ?", contractor_params[:number], contractor_params[:email]).first_or_initialize
    info_text = "We found an existing contractor that matched some of the details you entered. You can add a job for this contractor below."
    redirect_to @contractor, info: info_text and return if @contractor.persisted?

    # TODO: Support partners
    # added_by = current_user&.partner || current_user
    added_by = current_user
    @contractor.assign_attributes(contractor_params.merge(added_by:))
    respond_to do |format|
      if @contractor.save
        format.html { redirect_to @contractor, notice: "Contractor was successfully created." }
        format.json { render :show, status: :created, location: @contractor }
      else
        @trades = Trade.all
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @contractor.assign_attributes(contractor_params)
    @contractor.trade_ids = contractor_params[:trade_ids]
    @contractor.updated_by_id = current_user.id

    respond_to do |format|
      if @contractor.save
        format.html { redirect_to @contractor, notice: "Contractor was successfully updated." }
        format.json { render :show, status: :ok, location: @contractor }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contractor.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_contractor
    @contractor = Contractor.find(params.expect(:id))
  end

  def set_trades
    @trades = Trade.all
  end

  # Only allow a list of trusted parameters through.
  def contractor_params
    params.expect(contractor: [ :name, :company_name, :number, :email, :town, { trade_ids: [] } ])
  end
end

app/helpers/contractors_helper.rb
module ContractorsHelper
end

app/views/contractors/_contractor.html.erb
<% if action_name == "show" %>
  <h1 class="page-title brand"><%= contractor.name %> <%= " - " + contractor.company_name if contractor.company_name%></h1>
<% end %>

<div class="contractor card<%= " columns" if action_name == "index" %>" id="<%= dom_id contractor %>">
  <% unless action_name == "show" %>
    <%= link_to contractor, class: "" do %>
      <div class="card-header">
        <h3 class="name"><%= contractor.name %></h3>
        <h3 class="company"><%= contractor.company_name %></h3>
      </div>
    <% end %>
  <% end %>
  <div class="card-body<%= " rounded-top-corners" if action_name == "show" %>">
    <div class="row">
      <div class="trades">
        <% contractor.trades.each do |trade| %>
          <p class="btn btn-sm btn-<%= trade.name %>"><%= trade.name %></p>
        <% end %>
      </div>
    </div>
    <div class="row contractor-details">
      <div class="col">
        <p class="contractor-rating <%= contractor.rating_quality(current_user) %>-rating">
          <i class="fa-solid fa-star-half-stroke"></i>&nbsp;
          <% if contractor.viewable_ratings(current_user).present? %>
            Rated <%= contractor.average_rating(current_user) %> from
            <%= pluralize(contractor.viewable_ratings(current_user).size, "rating") %>
          <% else %>
            Not rated by anyone in your network
          <% end %>
        </p>
        <p>
          <i class="fa-solid fa-hammer"></i>&nbsp;
          <% if contractor.viewable_jobs(current_user).present? %>
            <%= pluralize(contractor.viewable_jobs(current_user).size, "job") %> for
            <%= pluralize(contractor.viewable_customers(current_user).size, "customer") %>
          <% else %>
            No jobs added by anyone in your network
          <% end %>
        </p>

        <p><i class="fa-solid fa-phone"></i>&nbsp;<%= contractor.number %></p>

        <% if contractor.email.present? %>
          <p><i class="fa-solid fa-envelope"></i>&nbsp;<%= contractor.email %></p>
        <% end %>

        <p><i class="fa-solid fa-location-dot"></i>&nbsp;<%= contractor.town %></p>

        <p>
          Added by:
          <%= contractor.added_by.full_name %>, <%= time_ago_in_words(contractor.created_at) %> ago
        </p>

        <% if contractor.updated_by_id.present? %>
          <p>
            Last Updated by:
            <%= contractor.updated_by.full_name %>, <%= time_ago_in_words(contractor.updated_at) %> ago
          </p>
        <% end %>
      </div>

    </div>
  </div>

  <div class="card-footer">
    <% if controller_name == "contractors" && action_name == "index" %>
      <%= link_to "See more details", contractor %>
    <% else %>
      <div class="flex">
        <div class="me-auto">
          <% if @user_is_customer %>
            <% if @user_rating.present? %>
              <p>Your Rating: <%= @user_rating.overall_rating %>/10</p>
              <%= link_to "Add another Job", new_contractor_job_path(contractor), class: "btn btn-success" %>
              <%= link_to "Update Rating", edit_contractor_rating_path(contractor, @user_rating), class: "btn btn-secondary" %>
            <% else %>
              <p>You've added a job, do you want to give <%= contractor.name %> a rating?</p>
              <%= link_to "Add a Rating", new_contractor_rating_path(contractor), class: "btn btn-success" %>
            <% end %>
          <% else %>
            <p> Has <%= contractor.name %> done a job for you? </p>
            <%= link_to "Add a Job", new_contractor_job_path(contractor), class: "btn btn-success" %>
          <% end %>
        </div>
        <div class="align-self-end">
          <%= link_to "Edit Details", edit_contractor_path(contractor), class: "btn btn-warning" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/contractors/_form.html.erb
<%= form_with(model: contractor) do |form| %>
  <% if contractor.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contractor.errors.count, "error") %> prohibited this contractor from being saved:</h2>

      <ul>
        <% contractor.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="field">
      <%= form.text_field :name, placeholder: "E.G. Bob Plumber", class: "form-input", required: true %>
      <%= form.label :name, class: "form-label floating-label" %>
    </div>
    <div class="field">
      <%= form.text_field :company_name, placeholder: "Bob's Plumber LTD", class: "form-input" %>
      <%= form.label :company_name, class: "form-label floating-label" %>
    </div>
  </div>

  <div class="row">
    <div class="field">
      <%= form.text_field :number, placeholder: "07696234890", class: "form-input", required: true %>
      <%= form.label :number, class: "form-label floating-label" %>
    </div>
    <div class="field">
      <%= form.email_field :email, placeholder: "bob@plumbing.job", class: "form-input" %>
      <%= form.label :email, class: "form-label floating-label" %>
    </div>

  </div>

  <div class="row">
    <div class="field center">
      <%= form.text_field :town, placeholder: "Swansea", class: "form-input", required: true %>
      <%= form.label :town, class: "form-label floating-label" %>
    </div>
  </div>

  <div class="row">
    <div class="field center slim-select">
      <%= form.collection_select :trade_ids, @trades, :id, :name,
                                 {},
                                 { multiple: true, class: "form-input",
                                   data: { controller: "slim-select",
                                           slim_select_placeholder: "Select Trades" } } %>
      <%= form.label :trade_ids, "Trades", class: "form-label floating-label" %>
    </div>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/contractors/edit.html.erb
<% content_for :title, "Editing contractor" %>
<main class="container">
  <div class="card form-card">
    <h1>Editing <%= @contractor.name %></h1>

    <%= render "form", contractor: @contractor %>
  </div>

  <hr>

  <div>
    <%= link_to "Show this contractor", @contractor %> |
    <%= link_to "Back to contractors", contractors_path %>
  </div>
</main>

app/views/contractors/index.html.erb
<% content_for :title, "Contractors" %>

<header id="contractors-header">
  <h1 class="page-title brand">Contractors in your Radius</h1>
  <div class="btn-container">
    <%= link_to "New contractor", new_contractor_path, class: "btn btn-primary" %>
  </div>

  <div class="trade-filters">
    <h3>Filter by Trade</h3>
    <div class="filter-buttons trades">
      <%= link_to "Clear Filter", contractors_path(search: params[:search]),
                  class: "trade-filter btn btn-#{params[:trade_id].blank? ? "secondary" : "primary"}" %>
      <% @trades.each do |trade| %>
        <%= link_to trade.name, contractors_path(trade_id: trade.id, search: params[:search]),
                    class: "trade-filter btn btn-#{params[:trade_id] == trade.id.to_s ? "secondary" : "primary"}" %>
      <% end %>
    </div>
  </div>

  <div class="search">
    <h3>Search</h3>
    <%= form_with url: contractors_path, method: :get, class: "row" do |form| %>
      <div class="label">
        <%= form.label :search, "By name, company name, number or email", class: "col-form-label" %>
      </div>
      <div class="field">
        <%= form.search_field :search, placeholder: "Search by name, number or email",
                              class: "form-input",
                              value: params[:search].present? ? params[:search] : "" %>
        <%= form.hidden_field :trade_id, value: params[:trade_id] if params[:trade_id].present? %>
      </div>

      <div class="actions">
        <%= form.submit "Search", class: "btn btn-success" %>
        <%= link_to "Clear Search", contractors_path(trade_id: params[:trade_id]), class: "btn btn-sm btn-warning" if params[:search].present? %>
      </div>
    <% end %>
  </div>
</header>

<main id="contractors">
  <% if @contractors.present? %>
    <% @contractors.each do |contractor| %>
      <%= render contractor %>
    <% end %>
  <% else %>
    <h1>No Contractors Found</h1>
  <% end %>
</main>

app/views/contractors/new.html.erb
<% content_for :title, "New contractor" %>
<main class="contractor-form">
  <div class="card form-card">
    <h1>Add a new contractor</h1>
    <%= render "form", contractor: @contractor %>
  </div>
  <hr>
  <div>
    <%= link_to "Back to contractors", contractors_path %>
  </div>
</main>

app/views/contractors/show.html.erb
<main id="contractor">
  <%= render @contractor %>

  <% if @user_jobs.present? %>
    <hr>
    <section class="jobs">
      <h2>Jobs <%= @contractor.name %> has done for you</h2>
      <div class="row">
        <% @user_jobs.each do |job| %>
          <%= render job %>
        <% end %>
      </div>
    </section>
  <% end %>

  <% if @viewable_ratings.present? %>
    <hr>
    <section class="ratings">
      <h2>Ratings <%= @contractor.name %> has received</h2>
      <div class="row">
        <% @viewable_ratings.each do |rating| %>
          <%= render rating %>
        <% end %>
      </div>
    </section>
  <% end %>

  <%= link_to "Back to contractors", contractors_path %>
</main>